services:
  - type: web
    name: ubatan-cacau-backend
    env: node
    region: oregon
    plan: free
    rootDir: ./backend
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000